```{r}
source("Rscripts/utils.R")
black_list <- my_read_bed("/mmfs1/gscratch/stergachislab/sjn/data/blacklist/hg38-blacklist.v2.sort.bed")
```

# read manifest and make super tables
```{r}
# dsg_fire_peaks	fire_peaks_dsa_to_hg38
manifest <- fread("Tables/sample-and-file-manifest.tsv") %>%
    select(
        ID, Individual_ID, PS, Platform,
        dsg_fire_peaks, fire_peaks_dsa_to_hg38
    ) %>%
    rowwise() %>%
    mutate(
        files_exists = file.exists(dsg_fire_peaks) & file.exists(fire_peaks_dsa_to_hg38)
    ) %>%
    as.tibble()
table(manifest$files_exists)
clean_manifest <- manifest %>%
    filter(files_exists) %>%
    select(-files_exists)
clean_manifest %>% filter(Individual_ID == "HG002")
```

```{r}
peaks <- my_read_bed(cmd = "bgzip -cd -@ 16 Tables/All-DSG-peaks.tsv.gz") %>%
    filter(ID %in% unique(clean_manifest$ID)) # %>%filter(autosome == "Autosomes")

filter(peak_id %in% unique(peaks$peak_id))
```

```{r}
is_blacklist <- peaks %>%
    filter(
        # !grepl("chrX|chrY", chrom),
    ) %>%
    mutate(
        chrom = hg38_chrom,
        start = hg38_start,
        end = hg38_end,
    ) %>%
    bed_map(
        black_list,
        in_blacklist = n() > 0,
    ) %>%
    replace_na(list(in_blacklist = FALSE)) %>%
    select(in_blacklist) %>%
    data.table()
nrow(peaks)
nrow(is_blacklist)
peaks$in_blacklist <- is_blacklist$in_blacklist
```


```{r}
peaks_with_38_info <- peaks %>%
    mutate(
        lifts_to_38 = !in_blacklist & !is.na(hg38_start),
    )
nrow(peaks_with_38_info)
```

```{r}
lift_summary <- peaks_with_38_info %>%
    group_by(Sample, PS, haplotype, Technology) %>%
    summarise(
        n_peaks = n(),
        n_peaks_lift_38 = sum(lifts_to_38),
        frac_lift_38 = n_peaks_lift_38 / n_peaks,
        n_sd_peaks = sum(is_SD),
        n_sd_peaks_lift_38 = sum(is_SD & lifts_to_38),
        frac_sd_lift_38 = n_sd_peaks_lift_38 / n_sd_peaks,
        frac_unlifted_that_are_sd = (n_sd_peaks - n_sd_peaks_lift_38) / (n_peaks - n_peaks_lift_38)
    ) %>%
    arrange(desc(frac_lift_38))
```

# plot lift summary as a violin with beswarm using ggrepel to plot the median 
```{r}
lift_summary %>%
    mutate(
        frac_unlifted = 1 - frac_lift_38,
    ) %>%
    pivot_longer(
        cols = c(frac_unlifted, frac_unlifted_that_are_sd),
        names_to = "type",
        values_to = "value"
    ) %>%
    # filter(frac_lift_38 > 0) %>%
    ggplot(aes(x = "", y = value)) +
    geom_violin(fill = "lightgray") +
    # geom_jitter(width=0.1, size=2, alpha=0.7) +
    geom_quasirandom(method = "pseudorandom", size = 1, alpha = 0.7) +
    geom_label_repel(
        data = . %>%
            group_by(type) %>%
            summarise(
                median_stat = median(value),
            ),
        aes(x = "", y = median_stat, label = paste0("Median: ", round(median_stat * 100, 2), "%")),
        # nudge_x = 0.2,
        size = 1.5,
        alpha = 0.8,
        min.segment.length = 0,
    ) +
    scale_y_continuous(
        "% of regulatory elements\nnot lifting to GRCh38",
        labels = scales::percent_format(),
        limits = c(0, NA)
    ) +
    facet_row(~type, scale = "free_y") +
    # rename the facets used in facet_row
    scale_x_discrete("") +
    my_grid()
my_ggsave("Figures/compare-to-38-fraction-peaks-not-lifting-to-38.pdf", width = 2, height = 2)
```

```{r}
# a plot of the chromosomes that do not lift and the n for each chrom
library(stringi)
levels <- c(paste0("chr", c(1:22, "X", "Y", "Un")), "")
peaks_with_38_info %>%
    filter(!lifts_to_38) %>%
    mutate(
        chrom_hg38 = gsub("_.*", "", chrom_hg38),
        chrom_hg38 = factor(chrom_hg38, levels = rev(levels)),
    ) %>%
    group_by(chrom_hg38) %>%
    summarise(
        n_peaks_not_lifting = n(),
    ) %>%
    ggplot(aes(y = chrom_hg38, x = n_peaks_not_lifting)) +
    geom_bar(stat = "identity", fill = "darkred") +
    scale_x_continuous(
        "Number of regulatory elements not lifting to GRCh38",
        labels = scales::comma_format()
    ) +
    ylab("") +
    my_grid()

my_ggsave(
    "Figures/compare-to-38-number-peaks-not-lifting-to-38-by-chromosome.pdf",
    width = 4,
    height = 2
)
```



```{r}
# show this on an ideogram of just HG002
peaks %>%
    filter(Sample == "HG002") %>%
    mutate(
        chrom_hg38 = gsub("_.*", "", chrom_hg38),
    ) %>%
    ggplot(
        aes(
            x = start,
            color = lifts_to_38,
        )
    ) +
    facet_col(~chrom) +
    geom_histogram(
        binwidth = 1e6,
    ) +
    scale_x_continuous(
        "HG002 position (Mb)",
        labels = comma
    ) +
    my_grid()

my_ggsave(
    "Figures/compare-to-38-HG002-peaks-not-lifting-to-38-ideogram.pdf",
    width = 6,
    height = 2
)
```
